export const users = [
  {
    id: 1,
    name: "John Doe",
    role: "DEVELOPER",
    status: "Present",
    storyPoints: 47,
    totalTime: "127:45",
  },
  {
    id: 2,
    name: "Sarah Chen",
    role: "DEVELOPER",
    status: "Present",
    storyPoints: 52,
    totalTime: "134:20",
  },
  {
    id: 3,
    name: "Mike Johnson",
    role: "HR",
    status: "Absent",
    storyPoints: 23,
    totalTime: "67:30",
  },
  {
    id: 4,
    name: "Emily Davis",
    role: "ADMIN",
    status: "Present",
    storyPoints: 38,
    totalTime: "98:15",
  },
  {
    id: 5,
    name: "Alex Kumar",
    role: "DEVELOPER",
    status: "Present",
    storyPoints: 41,
    totalTime: "112:40",
  },
];