export const userTasks = {
  1: [
    {
      id: "t1",
      title: "Login Page Design",
      status: "ongoing",
      priority: "High",
      assignedDate: "2025-01-20",
      assignedBy: "Emily Davis",
      timeSpent: "02:30",
    },
    {
      id: "t2",
      title: "Password Reset Feature",
      status: "completed",
      priority: "Medium",
      assignedDate: "2025-01-19",
      assignedBy: "Sarah Chen",
      timeSpent: "04:15",
    },
  ],
  2: [
    {
      id: "t3",
      title: "Database Schema",
      status: "pending",
      priority: "High",
      assignedDate: "2025-01-21",
      assignedBy: "John Doe",
      timeSpent: "00:00",
    },
    {
      id: "t4",
      title: "Data Validation",
      status: "ongoing",
      priority: "Medium",
      assignedDate: "2025-01-20",
      assignedBy: "Mike Johnson",
      timeSpent: "01:45",
    },
  ],
  3: [
    {
      id: "t5",
      title: "Employee Onboarding",
      status: "scheduled",
      priority: "Low",
      assignedDate: "2025-01-22",
      assignedBy: "Lisa Wang",
      timeSpent: "00:00",
    },
  ],
  4: [
    {
      id: "t6",
      title: "System Backup",
      status: "completed",
      priority: "High",
      assignedDate: "2025-01-18",
      assignedBy: "Alex Kumar",
      timeSpent: "03:20",
    },
    {
      id: "t7",
      title: "Security Audit",
      status: "ongoing",
      priority: "High",
      assignedDate: "2025-01-21",
      assignedBy: "David Brown",
      timeSpent: "05:10",
    },
  ],
  5: [
    {
      id: "t8",
      title: "Code Review",
      status: "pending",
      priority: "Medium",
      assignedDate: "2025-01-21",
      assignedBy: "Emma Wilson",
      timeSpent: "00:00",
    },
  ],
  6: [
    {
      id: "t9",
      title: "UI Testing",
      status: "ongoing",
      priority: "Low",
      assignedDate: "2025-01-20",
      assignedBy: "John Doe",
      timeSpent: "02:00",
    },
  ],
  7: [
    {
      id: "t10",
      title: "Payroll System",
      status: "due",
      priority: "High",
      assignedDate: "2025-01-15",
      assignedBy: "Sarah Chen",
      timeSpent: "01:30",
    },
  ],
  8: [
    {
      id: "t11",
      title: "Server Maintenance",
      status: "cancelled",
      priority: "Medium",
      assignedDate: "2025-01-19",
      assignedBy: "Mike Johnson",
      timeSpent: "00:45",
    },
  ],
};