import { useState } from "react";

const useTask = () => {
  const [userTasks, setUserTasks] = useState({
       1: [
         {
           id: "t1",
           title: "Login Page Design",
           status: "ongoing",
           priority: "High",
           assignedDate: "2025-01-20",
           assignedBy: "Emily Davis",
           timeSpent: "02:30:00",
           description: "Design the login page UI",
           deadline: "2025-01-25",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-01-20" },
             { status: "pending", date: "2025-01-20" },
             { status: "ongoing", date: "2025-01-21" },
           ],
           comments: [
             {
               id: "c1",
               author: "John Doe",
               text: "Started working on this.",
               date: "2025-01-21",
               replies: [
                 {
                   id: "r1",
                   author: "Emily Davis",
                   text: "Looks good!",
                   date: "2025-01-22",
                   replies: [],
                 },
               ],
             },
           ],
         },
         {
           id: "t2",
           title: "Password Reset Feature",
           status: "completed",
           priority: "Medium",
           assignedDate: "2025-01-19",
           assignedBy: "Sarah Chen",
           timeSpent: "04:15:00",
           description: "Implement password reset",
           deadline: "2025-01-24",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-01-19" },
             { status: "pending", date: "2025-01-19" },
             { status: "ongoing", date: "2025-01-20" },
             { status: "review", date: "2025-01-23" },
             { status: "completed", date: "2025-01-24" },
           ],
           comments: [],
         },
         {
           id: "p1-1",
           title: "Pending Task 1",
           status: "pending",
           priority: "Low",
           assignedDate: "2025-09-10",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Pending description",
           deadline: "2025-09-20",
           project: "MOL",
           history: [{ status: "created", date: "2025-09-10" }],
           comments: [],
         },
         {
           id: "p1-2",
           title: "Pending Task 2",
           status: "pending",
           priority: "High",
           assignedDate: "2025-09-11",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Another pending",
           deadline: "2025-09-21",
           project: "PRET-A-MED",
           history: [{ status: "created", date: "2025-09-11" }],
           comments: [],
         },
         {
           id: "r1-1",
           title: "Review Task 1",
           status: "review",
           priority: "Medium",
           assignedDate: "2025-09-12",
           assignedBy: "Admin",
           timeSpent: "01:00:00",
           description: "Review this",
           deadline: "2025-09-22",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-12" },
             { status: "ongoing", date: "2025-09-13" },
             { status: "review", date: "2025-09-14" },
           ],
           comments: [
             {
               id: "c2",
               author: "Admin",
               text: "Needs review.",
               date: "2025-09-14",
               replies: [],
             },
           ],
         },
         {
           id: "c1-1",
           title: "Cancelled Task 1",
           status: "in-queue",
           priority: "Low",
           assignedDate: "2025-09-13",
           assignedBy: "Admin",
           timeSpent: "00:30:00",
           description: "Cancelled",
           deadline: "2025-09-23",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-09-13" },
             { status: "in-queue", date: "2025-09-13" },
           ],
           comments: [],
         },
         {
           id: "s1-1",
           title: "Scheduled Task 1",
           status: "in-queue",
           priority: "High",
           assignedDate: "2025-09-14",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Scheduled",
           deadline: "2025-09-24",
           project: "MOL",
           history: [
             { status: "created", date: "2025-09-14" },
             { status: "in-queue", date: "2025-09-14" },
           ],
           comments: [],
         },
         {
           id: "f1-1",
           title: "Finished Task 1",
           status: "finished",
           priority: "Medium",
           assignedDate: "2025-09-15",
           assignedBy: "Admin",
           timeSpent: "03:00:00",
           description: "Finished",
           deadline: "2025-09-25",
           project: "PRET-A-MED",
           history: [
             { status: "created", date: "2025-09-15" },
             { status: "ongoing", date: "2025-09-16" },
             { status: "finished", date: "2025-09-17" },
           ],
           comments: [],
         },
       ],
       2: [
         {
           id: "t3",
           title: "Database Schema",
           status: "pending",
           priority: "High",
           assignedDate: "2025-01-21",
           assignedBy: "John Doe",
           timeSpent: "00:00:00",
           description: "Design schema",
           deadline: "2025-01-26",
           project: "DNCRP",
           history: [{ status: "created", date: "2025-01-21" }],
           comments: [],
         },
         {
           id: "t4",
           title: "Data Validation",
           status: "ongoing",
           priority: "Medium",
           assignedDate: "2025-01-20",
           assignedBy: "Mike Johnson",
           timeSpent: "01:45:00",
           description: "Validate data",
           deadline: "2025-01-25",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-01-20" },
             { status: "ongoing", date: "2025-01-21" },
           ],
           comments: [],
         },
         {
           id: "p2-1",
           title: "Pending Task 1",
           status: "pending",
           priority: "Low",
           assignedDate: "2025-09-10",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Pending",
           deadline: "2025-09-20",
           project: "MOL",
           history: [{ status: "created", date: "2025-09-10" }],
           comments: [],
         },
         {
           id: "r2-1",
           title: "Review Task 1",
           status: "review",
           priority: "High",
           assignedDate: "2025-09-11",
           assignedBy: "Admin",
           timeSpent: "00:45:00",
           description: "Review",
           deadline: "2025-09-21",
           project: "PRET-A-MED",
           history: [
             { status: "created", date: "2025-09-11" },
             { status: "review", date: "2025-09-12" },
           ],
           comments: [],
         },
         {
           id: "comp2-1",
           title: "Completed Task 1",
           status: "completed",
           priority: "Medium",
           assignedDate: "2025-09-12",
           assignedBy: "Admin",
           timeSpent: "02:00:00",
           description: "Completed",
           deadline: "2025-09-22",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-12" },
             { status: "completed", date: "2025-09-13" },
           ],
           comments: [],
         },
         {
           id: "c2-1",
           title: "Cancelled Task 1",
           status: "in-queue",
           priority: "Low",
           assignedDate: "2025-09-13",
           assignedBy: "Admin",
           timeSpent: "00:15:00",
           description: "Cancelled",
           deadline: "2025-09-23",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-09-13" },
             { status: "in-queue", date: "2025-09-13" },
           ],
           comments: [],
         },
         {
           id: "s2-1",
           title: "Scheduled Task 1",
           status: "in-queue",
           priority: "High",
           assignedDate: "2025-09-14",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Scheduled",
           deadline: "2025-09-24",
           project: "MOL",
           history: [
             { status: "created", date: "2025-09-14" },
             { status: "in-queue", date: "2025-09-14" },
           ],
           comments: [],
         },
         {
           id: "f2-1",
           title: "Finished Task 1",
           status: "finished",
           priority: "Medium",
           assignedDate: "2025-09-15",
           assignedBy: "Admin",
           timeSpent: "04:00:00",
           description: "Finished",
           deadline: "2025-09-25",
           project: "PRET-A-MED",
           history: [
             { status: "created", date: "2025-09-15" },
             { status: "finished", date: "2025-09-16" },
           ],
           comments: [],
         },
       ],
       3: [
         {
           id: "t5",
           title: "Employee Onboarding",
           status: "in-queue",
           priority: "Low",
           assignedDate: "2025-01-22",
           assignedBy: "Lisa Wang",
           timeSpent: "00:00:00",
           description: "Onboard employees",
           deadline: "2025-01-27",
           project: "HR Project",
           history: [{ status: "created", date: "2025-01-22" }],
           comments: [],
         },
         {
           id: "p3-1",
           title: "Pending Task 1",
           status: "pending",
           priority: "Medium",
           assignedDate: "2025-09-10",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Pending",
           deadline: "2025-09-20",
           project: "DNCRP",
           history: [{ status: "created", date: "2025-09-10" }],
           comments: [],
         },
         {
           id: "r3-1",
           title: "Review Task 1",
           status: "review",
           priority: "High",
           assignedDate: "2025-09-11",
           assignedBy: "Admin",
           timeSpent: "01:15:00",
           description: "Review",
           deadline: "2025-09-21",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-09-11" },
             { status: "review", date: "2025-09-12" },
           ],
           comments: [],
         },
         {
           id: "comp3-1",
           title: "Completed Task 1",
           status: "completed",
           priority: "Low",
           assignedDate: "2025-09-12",
           assignedBy: "Admin",
           timeSpent: "00:50:00",
           description: "Completed",
           deadline: "2025-09-22",
           project: "MOL",
           history: [
             { status: "created", date: "2025-09-12" },
             { status: "completed", date: "2025-09-13" },
           ],
           comments: [],
         },
         {
           id: "f3-1",
           title: "Finished Task 1",
           status: "finished",
           priority: "High",
           assignedDate: "2025-09-15",
           assignedBy: "Admin",
           timeSpent: "05:00:00",
           description: "Finished",
           deadline: "2025-09-25",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-15" },
             { status: "finished", date: "2025-09-16" },
           ],
           comments: [],
         },
       ],
       4: [
         {
           id: "t6",
           title: "System Backup",
           status: "completed",
           priority: "High",
           assignedDate: "2025-01-18",
           assignedBy: "Alex Kumar",
           timeSpent: "03:20:00",
           description: "Backup system",
           deadline: "2025-01-23",
           project: "Admin Project",
           history: [
             { status: "created", date: "2025-01-18" },
             { status: "completed", date: "2025-01-19" },
           ],
           comments: [],
         },
         {
           id: "t7",
           title: "Security Audit",
           status: "ongoing",
           priority: "High",
           assignedDate: "2025-01-21",
           assignedBy: "David Brown",
           timeSpent: "05:10:00",
           description: "Audit security",
           deadline: "2025-01-26",
           project: "Security",
           history: [
             { status: "created", date: "2025-01-21" },
             { status: "ongoing", date: "2025-01-22" },
           ],
           comments: [],
         },
         {
           id: "p4-1",
           title: "Pending Task 1",
           status: "pending",
           priority: "Low",
           assignedDate: "2025-09-10",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Pending",
           deadline: "2025-09-20",
           project: "DOLE",
           history: [{ status: "created", date: "2025-09-10" }],
           comments: [],
         },
         {
           id: "r4-1",
           title: "Review Task 1",
           status: "review",
           priority: "Medium",
           assignedDate: "2025-09-11",
           assignedBy: "Admin",
           timeSpent: "00:30:00",
           description: "Review",
           deadline: "2025-09-21",
           project: "MOL",
           history: [
             { status: "created", date: "2025-09-11" },
             { status: "review", date: "2025-09-12" },
           ],
           comments: [],
         },
         {
           id: "s4-1",
           title: "Scheduled Task 1",
           status: "in-queue",
           priority: "Low",
           assignedDate: "2025-09-14",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Scheduled",
           deadline: "2025-09-24",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-14" },
             { status: "in-queue", date: "2025-09-14" },
           ],
           comments: [],
         },
         {
           id: "f4-1",
           title: "Finished Task 1",
           status: "finished",
           priority: "Medium",
           assignedDate: "2025-09-15",
           assignedBy: "Admin",
           timeSpent: "02:30:00",
           description: "Finished",
           deadline: "2025-09-25",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-09-15" },
             { status: "finished", date: "2025-09-16" },
           ],
           comments: [],
         },
       ],
       5: [
         {
           id: "t8",
           title: "Code Review",
           status: "pending",
           priority: "Medium",
           assignedDate: "2025-01-21",
           assignedBy: "Emma Wilson",
           timeSpent: "00:00:00",
           description: "Review code",
           deadline: "2025-01-26",
           project: "Development",
           history: [{ status: "created", date: "2025-01-21" }],
           comments: [],
         },
         {
           id: "p5-1",
           title: "Pending Task 1",
           status: "pending",
           priority: "High",
           assignedDate: "2025-09-10",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Pending",
           deadline: "2025-09-20",
           project: "MOL",
           history: [{ status: "created", date: "2025-09-10" }],
           comments: [],
         },
         {
           id: "o5-1",
           title: "Ongoing Task 1",
           status: "ongoing",
           priority: "Low",
           assignedDate: "2025-09-11",
           assignedBy: "Admin",
           timeSpent: "00:45:00",
           description: "Ongoing",
           deadline: "2025-09-21",
           project: "PRET-A-MED",
           history: [
             { status: "created", date: "2025-09-11" },
             { status: "ongoing", date: "2025-09-12" },
           ],
           comments: [],
         },
         {
           id: "r5-1",
           title: "Review Task 1",
           status: "review",
           priority: "Medium",
           assignedDate: "2025-09-12",
           assignedBy: "Admin",
           timeSpent: "01:00:00",
           description: "Review",
           deadline: "2025-09-22",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-12" },
             { status: "review", date: "2025-09-13" },
           ],
           comments: [],
         },
         {
           id: "comp5-1",
           title: "Completed Task 1",
           status: "completed",
           priority: "High",
           assignedDate: "2025-09-13",
           assignedBy: "Admin",
           timeSpent: "03:00:00",
           description: "Completed",
           deadline: "2025-09-23",
           project: "DOLE",
           history: [
             { status: "created", date: "2025-09-13" },
             { status: "completed", date: "2025-09-14" },
           ],
           comments: [],
         },
         {
           id: "s5-1",
           title: "Scheduled Task 1",
           status: "in-queue",
           priority: "Medium",
           assignedDate: "2025-09-15",
           assignedBy: "Admin",
           timeSpent: "00:00:00",
           description: "Scheduled",
           deadline: "2025-09-25",
           project: "PRET-A-MED",
           history: [
             { status: "created", date: "2025-09-15" },
             { status: "in-queue", date: "2025-09-15" },
           ],
           comments: [],
         },
         {
           id: "f5-1",
           title: "Finished Task 1",
           status: "finished",
           priority: "High",
           assignedDate: "2025-09-16",
           assignedBy: "Admin",
           timeSpent: "06:00:00",
           description: "Finished",
           deadline: "2025-09-26",
           project: "DNCRP",
           history: [
             { status: "created", date: "2025-09-16" },
             { status: "finished", date: "2025-09-17" },
           ],
           comments: [],
         },
       ],
     });

  const moveTask = (userId, taskId, newStatus) => {
    setUserTasks((prev) => {
      const userT = prev[userId] || [];
      const taskIndex = userT.findIndex((t) => t.id === taskId);
      if (taskIndex === -1) return prev;
      const newTasks = [...userT];
      newTasks[taskIndex] = { ...newTasks[taskIndex], status: newStatus };
      return { ...prev, [userId]: newTasks };
    });
  };

  const updateTask = (userId, taskId, updates) => {
    setUserTasks((prev) => {
      const userT = [...(prev[userId] || [])];
      const taskIndex = userT.findIndex((t) => t.id === taskId);
      if (taskIndex === -1) return prev;
      userT[taskIndex] = { ...userT[taskIndex], ...updates };
      return { ...prev, [userId]: userT };
    });
  };

  const handleAddTask = (newTask, userId) => {
    newTask.id = `t${Date.now()}`;
    newTask.status = "pending";
    newTask.history = [
      { status: "created", date: new Date().toISOString().split("T")[0] },
    ];
    newTask.comments = [];
    setUserTasks((prev) => ({
      ...prev,
      [userId]: [...(prev[userId] || []), newTask],
    }));
  };

  return {
    userTasks,
    setUserTasks,
    moveTask,
    updateTask,
    handleAddTask
  };
};

export default useTask;